// Generated by PicoPixel.io — https://picopixel.io
#include <string.h>
#include <stdbool.h>

#include "screens.h"
#include "images.h"
#include "fonts/fonts.h"
#include "actions.h"
#include "vars.h"
#include "styles.h"
#include "ui.h"

objects_t objects;
lv_obj_t *tick_value_change_obj;
uint32_t active_theme_index = 0;

enum EmotionId {
    EMO_ANGRY = 0,
    EMO_CONFUSED,
    EMO_HAPPY,
    EMO_IDEAL,
    EMO_LOVE,
    EMO_PANIC,
    EMO_RECONNECTING,
    EMO_RIZZ,
    EMO_SAD,
    EMO_SEARCH_THINKING,
    EMO_SHY,
    EMO_SLEEP,
    EMO_SPEEKING,
    EMO_SURPRISED,
    EMO_COUNT
};

static void set_rect(lv_obj_t *obj, lv_coord_t x, lv_coord_t y, lv_coord_t w, lv_coord_t h, lv_coord_t radius) {
    if (obj == NULL) return;
    lv_obj_set_pos(obj, x, y);
    lv_obj_set_size(obj, w, h);
    lv_obj_set_style_radius(obj, radius, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(obj, lv_color_hex(0xffffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
}

static void apply_emotion(enum EmotionId emotion) {
    if (objects.eyel == NULL || objects.eyer == NULL || objects.mouth == NULL) return;

    // Base face geometry (black background + white primitives).
    set_rect(objects.eyel, 37, 51, 70, 20, 20);
    set_rect(objects.eyer, 204, 51, 70, 20, 20);
    set_rect(objects.mouth, 120, 154, 80, 20, 20);

    switch (emotion) {
        case EMO_ANGRY:
            set_rect(objects.eyel, 37, 56, 70, 10, 8);
            set_rect(objects.eyer, 204, 56, 70, 10, 8);
            set_rect(objects.mouth, 118, 156, 84, 8, 4);
            break;
        case EMO_CONFUSED:
            set_rect(objects.eyel, 37, 47, 70, 14, 10);
            set_rect(objects.eyer, 204, 58, 70, 14, 10);
            set_rect(objects.mouth, 152, 152, 16, 24, 8);
            break;
        case EMO_HAPPY:
            set_rect(objects.eyel, 37, 58, 70, 10, 10);
            set_rect(objects.eyer, 204, 58, 70, 10, 10);
            set_rect(objects.mouth, 126, 154, 68, 16, 16);
            break;
        case EMO_IDEAL:
            set_rect(objects.eyel, 37, 51, 70, 20, 20);
            set_rect(objects.eyer, 204, 51, 70, 20, 20);
            set_rect(objects.mouth, 120, 154, 80, 20, 20);
            break;
        case EMO_LOVE:
            set_rect(objects.eyel, 40, 48, 64, 24, 24);
            set_rect(objects.eyer, 206, 48, 64, 24, 24);
            set_rect(objects.mouth, 124, 156, 72, 14, 14);
            break;
        case EMO_PANIC:
            set_rect(objects.eyel, 45, 45, 54, 30, 30);
            set_rect(objects.eyer, 221, 45, 54, 30, 30);
            set_rect(objects.mouth, 145, 146, 30, 34, 18);
            break;
        case EMO_RECONNECTING:
            set_rect(objects.eyel, 37, 61, 70, 7, 4);
            set_rect(objects.eyer, 204, 61, 70, 7, 4);
            set_rect(objects.mouth, 132, 158, 56, 8, 4);
            break;
        case EMO_RIZZ:
            set_rect(objects.eyel, 37, 54, 70, 18, 18);
            set_rect(objects.eyer, 204, 54, 70, 18, 18);
            set_rect(objects.mouth, 124, 150, 72, 10, 5);
            break;
        case EMO_SAD:
            set_rect(objects.eyel, 37, 63, 70, 10, 10);
            set_rect(objects.eyer, 204, 63, 70, 10, 10);
            set_rect(objects.mouth, 126, 166, 68, 10, 10);
            break;
        case EMO_SEARCH_THINKING:
            set_rect(objects.eyel, 43, 50, 58, 22, 22);
            set_rect(objects.eyer, 204, 53, 70, 18, 18);
            set_rect(objects.mouth, 130, 154, 60, 10, 5);
            break;
        case EMO_SHY:
            set_rect(objects.eyel, 37, 60, 70, 8, 6);
            set_rect(objects.eyer, 204, 60, 70, 8, 6);
            set_rect(objects.mouth, 130, 156, 60, 14, 14);
            break;
        case EMO_SLEEP:
            set_rect(objects.eyel, 37, 64, 70, 6, 3);
            set_rect(objects.eyer, 204, 64, 70, 6, 3);
            set_rect(objects.mouth, 138, 162, 44, 6, 3);
            break;
        case EMO_SPEEKING:
            set_rect(objects.eyel, 37, 52, 70, 18, 18);
            set_rect(objects.eyer, 204, 52, 70, 18, 18);
            set_rect(objects.mouth, 144, 146, 32, 36, 16);
            break;
        case EMO_SURPRISED:
            set_rect(objects.eyel, 45, 44, 54, 30, 30);
            set_rect(objects.eyer, 221, 44, 54, 30, 30);
            set_rect(objects.mouth, 146, 148, 28, 32, 16);
            break;
        default:
            break;
    }
}

void create_screen_screen_1() {
    lv_obj_t *obj = lv_obj_create(0);
    objects.screen_1 = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 320, 240);
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_pad_all(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    {
        lv_obj_t *parent_obj = obj;
        {
            // eyel
            lv_obj_t *obj = lv_obj_create(parent_obj);
            objects.eyel = obj;
            lv_obj_set_pos(obj, 37, 51);
            lv_obj_set_size(obj, 70, 20);
            lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
            lv_obj_set_style_pad_all(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_color(obj, lv_color_hex(0xffffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        }
        {
            // eyer
            lv_obj_t *obj = lv_obj_create(parent_obj);
            objects.eyer = obj;
            lv_obj_set_pos(obj, 204, 51);
            lv_obj_set_size(obj, 70, 20);
            lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
            lv_obj_set_style_pad_all(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_color(obj, lv_color_hex(0xffffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        }
        {
            // mouth
            lv_obj_t *obj = lv_obj_create(parent_obj);
            objects.mouth = obj;
            lv_obj_set_pos(obj, 120, 154);
            lv_obj_set_size(obj, 80, 20);
            lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
            lv_obj_set_style_pad_all(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_color(obj, lv_color_hex(0xffffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        }
    }

    tick_screen_screen_1();
}

void tick_screen_screen_1() {
    static uint32_t last_switch_ms = 0;
    static bool initialized = false;
    static uint8_t current_emotion = 0;

    if (!initialized) {
        apply_emotion((enum EmotionId)current_emotion);
        last_switch_ms = lv_tick_get();
        initialized = true;
        return;
    }

    if (lv_tick_elaps(last_switch_ms) >= 5000) {
        last_switch_ms = lv_tick_get();
        current_emotion = (uint8_t)((current_emotion + 1) % EMO_COUNT);
        apply_emotion((enum EmotionId)current_emotion);
    }
}



typedef void (*tick_screen_func_t)();
tick_screen_func_t tick_screen_funcs[] = {
    tick_screen_screen_1,
};
void tick_screen(int screen_index) {
    tick_screen_funcs[screen_index]();
}
void tick_screen_by_id(enum ScreensEnum screenId) {
    tick_screen_funcs[screenId - 1]();
}

void delete_screen_screen_1() {
    if (objects.screen_1 != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects.screen_1);
        lv_obj_del(objects.screen_1);
    }
    objects.screen_1 = 0;
    objects.eyel = 0;
    objects.eyer = 0;
    objects.mouth = 0;
}


typedef void (*delete_screen_func_t)();
delete_screen_func_t delete_screen_funcs[] = {
    delete_screen_screen_1,
};
void delete_screen_by_id(enum ScreensEnum screenId) {
    delete_screen_funcs[screenId - 1]();
}

void create_screens() {
    lv_disp_t *dispp = lv_disp_get_default();
    // Use dark theme (true) to match the editor's appearance - white text on dark buttons
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);

    create_screen_screen_1();
}
